import {Domine}  from "next/font/google"

const domine = Domine({
weight: "400",
subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={domine.className}>
        {children}
      </body>
    </html>
  );
}
